### ISSUE TITLE
Support more gates in Yao

### ISSUE THREAD

**Issue by Sov-trotter** [Sov-trotter/IBMQJulia.jl#1]
https://github.com/Sov-trotter/IBMQ-Julia/issues/1

 GiggleLiu commented 5 minutes ago

Transform YaoBlocks to basic form, so that the RepeatBlock et. al will be translated to equivalent elementary form that containing only chain, put and primitive blocks.
    https://github.com/QuantumBFS/YaoPlots.jl/blob/7a68da39aae2d92bb26d2d636c8da6cb46703b3a/src/vizcircuit.jl#L171

This will make the circuit much easier to handle. Better error handling for not supported gates.

**Comment by Sov-trotter** [comment]
@GiggleLiu So I did try out the above simplification method and this looks cool.  https://github.com/Sov-trotter/IBMQJulia.jl/blob/main/src/qobj.jl#L12

Sorry. I hastily committed to main rather than working it out in a PR.

**Comment by GiggleLiu** [comment]
No worries. It looks good. I can submit a PR to add some tests later.

**Comment by Sov-trotter** [comment]
Ah great. For the tests I am a bit unsure. We can obviously write ones for the Qobj part but I was wondering what could we do for the part where web stuff like the post/get/put requests are involved. The Python way I saw was creating a dummy server?

**Comment by GiggleLiu** [comment]
Yeah, we can create a dummy server too. But I meant testing the generated gate sequence first.

**Comment by Sov-trotter** [comment]
I think this can be closed in favor of more specific discussion over other issues
