### ISSUE TITLE
Use gates outside basis_gates

### ISSUE THREAD

**Issue by Sov-trotter** [Sov-trotter/IBMQJulia.jl#13]
In the step 2 in the Readme, while creating a `IBMQReg` the user is given a choice of backends. For each backend the interface lists out the number of qubits and basis_gates supported by the backend. 
Now if we try to run higher qubits or gates outside the basis_gates of any backend, we get a `ERROR_RUNNING_JOB` return value. 
For eg : `ibm_santiago` supports  `basis_gates=Any["id", "u1", "u2", "u3", "cx"]`. Now if my circuit contains the gate `rx`, it will return `ERROR_RUNNING_JOB`. 

Apparently one might conclude that it;s not possible to run certain gates on some backends. Surprisingly, rx, ry, rz gates are not supported by ibm_qasm_simulator too! But the qasm specification does list it here https://github.com/Qiskit/openqasm/blob/master/examples/generic/qelib1.inc#L38-L42. 

I wonder if we're missing something here? Do we need to represent those gates in terms of the supported gates for each backend(eg: rz interms of other gates if possible)? Or is the basis_gates list sort of misleading?

I'd really love to discuss this here before asking the IBMQ folks?
Any ideas @Roger-luo @GiggleLiu

**Comment by Roger-luo** [comment]
interesting, cuz I thought their QASM simulator supports that since it's open-sourced in qiskit. I got more time to check this now, I'll have a look later this week.

**Comment by VarLad** [comment]
> Surprisingly, rx, ry, rz gates are not supported by ibm_qasm_simulator too! 
```
OPENQASM 2.0;
include "qelib1.inc";
gate nG0 ( param ) q  {
  h q;
}

qreg q[3];
creg c[3];

rx(pi/2) q[0];
ry(pi/2) q[1];
rz(pi/2) q[2];
```
I think this works....
Pardon me if I'm misunderstanding....😅

**Comment by GiggleLiu** [comment]
In case we really need to compile gates, we can start from defining/aliasing those basis gates in IBM Q, their matrix are defined in
https://qiskit.org/documentation/apidoc/circuit_library.html

It should good to follow the dedinition of FSim gate
https://github.com/QuantumBFS/YaoExtensions.jl/blob/2b99dde6628480349f3c6018808590b82ca4961e/src/block_extension/FSimGate.jl#L5

Then, we can add more simplification pass on top of that. The listing 4 in our paper shows how it works https://arxiv.org/abs/1912.10877

**Comment by Sov-trotter** [comment]
Ah cool. I looked into ProjectQ once again and it seems that they have converted the gates like H, rx, rz etc. to their u1, u2, u3 equivalents receptively. https://github.com/ProjectQ-Framework/ProjectQ/blob/develop/projectq/backends/_ibm/_ibm.py#L90-L110
https://github.com/ProjectQ-Framework/ProjectQ/blob/develop/projectq/backends/_ibm/_ibm.py#L172-L182
I thought that the transpiling process would handle that but apparently it doesn't.

**Comment by Sov-trotter** [comment]
>I think this works.

Yeah things work when we use those gates in composer, which I think is handled in the background
![Screenshot from 2020-10-20 18-50-05](https://user-images.githubusercontent.com/43717431/96591677-22877900-1305-11eb-9dda-4733be716c6a.png)
So we'll have to basically write them into the form of single qubit unitary gates. During the qobj generation

**Comment by Sov-trotter** [comment]
https://github.com/Sov-trotter/IBMQJulia.jl/pull/12/commits/d465623fb45980287b900d865cb9f9c022c69912 Solves this (atleast for H and rotational gates). I'd love if while reviewing the PR one can verify that the conversions are correct. 
Ref: https://github.com/ProjectQ-Framework/ProjectQ/blob/develop/projectq/backends/_ibm/_ibm.py#L169-L187

**Comment by Roger-luo** [comment]
actually in YaoLang I compile things like `h` to rotations when the target is QASM as well. It's quite simple as long as the compiler is able to understand the QASM stdlib, since it's defined in QASM stdlib, so simply inline a routine call would do the job. I think we can just do the simplest things for YaoBlocks here would be sufficient. I'd like to have a more independent wrapper (which is the register here) so I can compile things to from YaoLang.
